version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - '.env'
    volumes:
      - ./container_data/influxdb:/var/lib/influxdb
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    env_file:
      - '.env'
    links:
      - influxdb
    volumes:
      - ./container_data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
