version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086" # HTTP service port
      - "8088:8088" # RPC service port
    env_file:
      - '.env'
    volumes:
      - influxdb-data:/var/lib/influxdb
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb-data:
  grafana-data:
